---
- name: "HLDC-Traefik"
  hosts: localhost
  connection: local
  vars:
    - install_dir: /usr/local/etc/traefik
    - certs_dir: /opt/traefik/certs
  tasks:

  - name: "Print Vars"
    debug:
      msg: "install_dir = {{ install_dir }}"

  - name: "Create app directory"
    file:
      path: "{{ install_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: "Create certs directory"
    file:
      path: "{{ certs_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: "Tear down existing services"
    community.docker.docker_compose:
      project_src: "{{ install_dir }}"
      state: absent
    ignore_errors: true

  - name: "Copy files"
    copy:
      src: "{{ item }}"
      dest: "{{ install_dir }}/{{ item }}"
    loop:
      - docker-compose.yml
      - .env.example

  - name: "Put up services"
    community.docker.docker_compose:
      project_src: "{{  install_dir }}"
      state: present
